### ISSUE TITLE
No module named pycasper

### ISSUE THREAD

**Issue by AhmedHashish123** [chahuja/mix-stage#6]
I followed the steps in the "Set Up Environment" section and a folder named pycasper was created. The problem is that this folder is outside "mix-stage" folder. So, files can't find the module. Should I transfer the pycasper directory inside "mix-stage" directory? Or  should I transfer it to the model directory inside src directory inside "mix-stage"?

**Comment by chahuja** [comment]
I would recommend running the following command after going to the folder mix-stage/src, 

```sh
cd mix-stage/src
ln -s ../../pycasper/pycasper .
```

This will create a symlink (or shortcut of the library inside of mix-stage). That should get rid of the errors.

Another way, which you suggested, is copying the pycasper directory inside of src. Just be careful and copy the `pycasper` folder within the `pycasper` github folder. 

```sh
cp -r pycasper/pycasper mix-stage/src
```

**Comment by AhmedHashish123** [comment]
Thanks, but now I get an error:
 Results Loaded
model.trainer.TrainerJointLateClusterStyleGAN selected
Results Loaded
Traceback (most recent call last):
  File "sample.py", line 34, in <module>
    argparseNloop(loop)
  File "/content/mix-stage/src/argsUtils.py", line 258, in argparseNloop
    loop(args, i)
  File "sample.py", line 21, in loop
    trainer = Trainer(args, args_subset, args_dict_update)
  File "/content/mix-stage/src/model/trainer.py", line 1346, in __init__
    super().__init__(args, args_subset, args_dict_update)
  File "/content/mix-stage/src/model/trainer.py", line 1245, in __init__
    super(TrainerGAN, self).__init__(args, args_subset, args_dict_update)
  File "/content/mix-stage/src/model/trainer.py", line 104, in __init__
    self.data, self.data_train, self.data_dev, self.data_test = self.get_data()
  File "/content/mix-stage/src/model/trainer.py", line 208, in get_data
    weighted=self.args.weighted, filler=self.args.filler, num_training_iters=self.args.num_training_iters)
  File "/content/mix-stage/src/data/dataUtils.py", line 92, in __init__
    super().__init__(path2data=path2data)
  File "/content/mix-stage/src/data/common.py", line 112, in __init__
    self.df = pd.read_csv(Path(self.path2data)/'cmu_intervals_df.csv', dtype=object)
  File "/usr/local/lib/python3.7/dist-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.7/dist-packages/pandas/io/parsers.py", line 454, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/usr/local/lib/python3.7/dist-packages/pandas/io/parsers.py", line 948, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python3.7/dist-packages/pandas/io/parsers.py", line 1180, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python3.7/dist-packages/pandas/io/parsers.py", line 2010, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] No such file or directory: '../data/cmu_intervals_df.csv'

when I try to get an example of sampling gesture animations from a pretrained model using the command that you provided in the repo:

python sample.py \
-load save/pretrained_models/multi-speaker/exp_3659_cpk_JointLateClusterSoftStyle4_G_speaker_\[\'corden\',\ \'lec_cosmic\'\]_model_JointLateClusterSoftStyle4_G_note_s2g_gst_mixgan15_weights.p \
-path2data ../data

**Comment by chahuja** [comment]
There should be a file at .. data/cmu_intervals_df.csv which is a part of
the dataset. Sample.py does not work without the dataset.

**Comment by AhmedHashish123** [comment]
Isn't there an inference script that takes a certain input and provides an output?

**Comment by AhmedHashish123** [comment]
I'm using the pretrained models so I thought that I wouldn't need the dataset

**Comment by chahuja** [comment]
Unfortunately not at the moment. This was just meant to recreate results of
the paper.

I'll probably get to writing such a script at some point, but not sure if
that's in the cards for the near future.

**Comment by AhmedHashish123** [comment]
Ok, thank you for replying.
